name: blackcoffer_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Firebase 
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  pinput: ^3.0.1
  intl_phone_field: ^3.2.0
  camera: ^0.10.5+5
  equatable: ^2.0.5
  video_player: ^2.7.2
  geolocator: ^10.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
